version: '3'
services:
  keymanager-grpc:
    build: ./
    restart: on-failure
    ports:
      - '50051:50051'
    depends_on:
      - postgres
      - bcb
      - erp-itau
    environment:
      DB_URL: jdbc:postgresql://:5432/keymanager
      DB_USER: keycloak
      DB_PASS: password
      ITAU_URL: http://erp-itau:9091
      BCB_URL: http://bcb:8082

  postgres:
    image: 'postgres:alpine'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keymanager
      POSTGRES_HOST: postgres

  bcb:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix"
    ports:
      - 8082:8082
  erp-itau:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
    ports:
      - 9091:9091

volumes:
  postgres-volume:
networks:
  network-grpc: