
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keymanager-grpc-helm.fullname" . }}-secret
  labels:
    {{- include "keymanager-grpc-helm.labels" . | nindent 8 }}
type: {{ .Values.secretType }}
stringData:
  DB_PASS: {{ .Values.DB_PASS | quote }}