micronaut:
  application:
    name: keymanagergrpc
datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/keymanager`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:`keycloak`}
    password: ${DB_PASS:`password`}
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: true

periodictask:
  initialdelay: ${TASK:5000ms}
  balancerdelay: ${TASK:7000ms}
