apiVersion: v1
kind: Service
metadata:
  name: {{ include "dependencies.fullname" . }}
  labels:
    {{- include "dependencies.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8082
      targetPort: bcb-port
      protocol: TCP
      name: bcb-port
    - port: 9091
      targetPort: erp-port
      protocol: TCP
      name: erp-port
    - port: 5432
      targetPort: db-port
      protocol: TCP
      name: db-port
  selector:
    {{- include "dependencies.selectorLabels" . | nindent 4 }}
