apiVersion: v1
kind: Pod
metadata:
  name: db-keymanager
  labels:
    app: db-keymanager
spec:
  containers:
    - name: db-keymanager-container
      image: postgres:alpine
      ports:
        - containerPort: 5432
      envFrom:
        - configMapRef:
            name: db-configmap