apiVersion: v1
kind: ConfigMap
metadata:
  name: keymanager-grpc-configmap
data:
  DB_URL: jdbc:postgresql://svc-db-keymanager:5432/keymanager
  DB_USER: keycloak
  ITAU_URL: http://erp-service:9091
  BCB_URL: http://bcb-service:8082